baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'faros.sh'
theme = 'coming-soon'
[params]
  release = '2024-06-01'
  description = 'faros.sh is distributed kubernetes management platform'
  title = 'faros.sh'
