#!/usr/bin/env python3
"""Copy the generated faros CLI reference into this site.

The faros repository generates one cobra markdown file per command under
docs/cli (``make docs-cli`` there). This script rewrites those files as Hugo
pages under content/en/docs/reference/cli/commands/ and regenerates the
sidebar for that section in data/docs.json.

Usage: scripts/sync-cli-docs.py --source ../faros/docs/cli
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "content/en/docs/reference/cli/commands"
NAV = ROOT / "data/docs.json"
BASE_URL = "/docs/reference/cli/commands/"
BANNER = "<!-- Generated by scripts/sync-cli-docs.py from faroshq/faros docs/cli. Do not edit by hand; run `make sync-cli-docs`. -->"

SECTION_TITLES = {
    "Synopsis": "Synopsis",
    "Examples": "Examples",
    "Options": "Options",
    "Options inherited from parent commands": "Inherited options",
    "SEE ALSO": "See also",
}
TEXT_FENCE_SECTIONS = {"Options", "Inherited options"}
SEE_ALSO = re.compile(r"^\* \[(?P<name>[^\]]+)\]\((?P<file>faros[^)]*)\.md\)\t? - (?P<desc>.*)$")


def slug_for(stem):
    """faros_skills_install -> skills-install; faros -> '' (section index)."""
    parts = stem.split("_")[1:]
    return "-".join(parts)


def url_for(stem):
    slug = slug_for(stem)
    return BASE_URL + (slug + "/" if slug else "")


def yaml_str(value):
    return json.dumps(value, ensure_ascii=False)


def escape_text(line):
    # Angle brackets outside code spans are raw HTML to goldmark and get dropped
    # with unsafe=false; escape them so "faros <command>" survives.
    out, in_code = [], False
    for ch in line:
        if ch == "`":
            in_code = not in_code
        elif ch == "<" and not in_code:
            out.append("\\")
        out.append(ch)
    return "".join(out)


def fence_indented_examples(lines):
    """Wrap runs of 2-space indented prose (cobra Long examples) in bash fences.

    Outside a fence markdown treats "  # comment" as a heading and "  faros ..."
    as a paragraph, so the examples in a command's synopsis lose their shape.
    """
    out, block, in_fence = [], [], False

    def flush():
        trailing = []
        while block and not block[-1].strip():
            trailing.append(block.pop())  # blank lines belong after the fence
        if block:
            out.append("```bash")
            out.extend(l[2:] if l.startswith("  ") else l for l in block)
            out.append("```")
        out.extend(trailing)
        block.clear()

    for line in lines:
        if line.startswith("```"):
            flush()
            in_fence = not in_fence
            out.append(line)
        elif in_fence:
            out.append(line)
        elif line.startswith("  "):
            block.append(line)
        elif block and not line.strip():
            block.append(line)
        else:
            flush()
            out.append(line)
    flush()
    return out


def convert(text):
    """Return (title, description, body) for one cobra markdown file."""
    lines = text.rstrip("\n").split("\n")
    if not lines or not lines[0].startswith("## "):
        raise ValueError("expected '## <command>' as the first line")
    title = lines[0][3:].strip()
    i = 1
    while i < len(lines) and not lines[i].strip():
        i += 1
    description = lines[i].strip() if i < len(lines) and not lines[i].startswith(("#", "```")) else ""
    if description:
        i += 1

    body, section, in_fence = [], "", False
    for line in fence_indented_examples(lines[i:]):
        if line.startswith("```"):
            if not in_fence and line.strip() == "```":
                line = "```text" if section in TEXT_FENCE_SECTIONS else "```bash"
            in_fence = not in_fence
            body.append(line)
            continue
        if in_fence:
            body.append(line)
            continue
        if line.startswith("### "):
            raw = line[4:].strip()
            section = SECTION_TITLES.get(raw, raw)
            body.append(f"## {section}")
            continue
        m = SEE_ALSO.match(line)
        if m:
            body.append(f"- [{m['name']}]({url_for(m['file'])}) — {escape_text(m['desc'])}")
            continue
        body.append(escape_text(line))
    return title, description, "\n".join(body).strip() + "\n"


def write_page(stem, title, description, body, weight):
    slug = slug_for(stem)
    if slug:
        path = DEST / f"{slug}.md"
        link_title = title.removeprefix("faros ").strip()
    else:
        path = DEST / "_index.md"
        title = "Command reference"
        link_title = "Command reference"
        description = "Every faros command with its flags and examples, generated from the CLI."
    front = [
        "---",
        f"title: {yaml_str(title)}",
        f"linkTitle: {yaml_str(link_title)}",
        f"description: {yaml_str(description)}",
        f"weight: {weight}",
        "doc_type: Reference",
        "generated: true",
        "---",
        BANNER,
        "",
        "",
    ]
    path.write_text("\n".join(front) + body)
    return path


def build_sidebar(commands):
    """commands: list of (stem, title, description). Group children under their parent."""
    top = {}
    for stem, title, _ in commands:
        parts = stem.split("_")[1:]
        if not parts:
            continue
        top.setdefault(parts[0], []).append((stem, title, len(parts)))
    leaf_links, groups = [], []
    for name in sorted(top):
        entries = sorted(top[name], key=lambda e: e[0])
        links = [{"url": url_for(stem), "title": title.removeprefix("faros ").strip()} for stem, title, _ in entries]
        if len(entries) == 1:
            leaf_links.extend(links)
        else:
            groups.append({"title": f"faros {name}", "links": links})
    return {
        "root": BASE_URL,
        "area": "reference",
        "generated": "scripts/sync-cli-docs.py",
        "groups": [{"title": "Commands", "links": leaf_links}] + groups,
    }


def update_nav(sidebar):
    nav = json.loads(NAV.read_text())
    sidebars = [s for s in nav["sidebars"] if s["root"] != BASE_URL]
    # Keep the generated sidebar right after the hand-written CLI reference one.
    index = next((i + 1 for i, s in enumerate(sidebars) if s["root"] == "/docs/reference/cli/"), len(sidebars))
    sidebars.insert(index, sidebar)
    nav["sidebars"] = sidebars
    NAV.write_text(json.dumps(nav, indent=2, ensure_ascii=False) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", required=True, help="path to the faros repository's docs/cli directory")
    args = parser.parse_args()
    source = Path(args.source).expanduser().resolve()
    files = sorted(source.glob("faros*.md"))
    if not files:
        sys.exit(f"no faros*.md files in {source}; run 'make docs-cli' in the faros repository first")

    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)

    commands = []
    for weight, path in enumerate(files, start=1):
        title, description, body = convert(path.read_text())
        write_page(path.stem, title, description, body, weight)
        commands.append((path.stem, title, description))

    update_nav(build_sidebar(commands))
    print(f"synced {len(commands)} command pages from {source} into {DEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
